export const DEFAULT_EDITOR_OPTIONS = {
  minimap: { enabled: true },
  fontSize: 13,
  padding: { top: 12, bottom: 12 },
  lineNumbers: 'on' as const,
  rulers: [],
  wordWrap: 'on' as const,
  automaticLayout: true,
  scrollBeyondLastLine: false,
  renderWhitespace: 'selection' as const,
  cursorBlinking: 'smooth' as const,
  smoothScrolling: true,
  formatOnPaste: true,
  formatOnType: true,
};
